name: simclr-cifar10-colab
dataset:
  name: cifar10
  image_size: 32
  num_workers: 0

model:
  name: simclr
  backbone: resnet18

train:
  optimizer:
    name: lars_simclr
    weight_decay: 1.e-6
  warmup_epochs: 10
  warmup_lr: 0
  base_lr: 0.3
  final_lr: 0
  num_epochs: 200
  stop_at_epoch: 200
  batch_size: 128
  source_pool_size: 1000
  source_subset_seed: 0
  knn_monitor: True
  knn_interval: 1
  knn_k: 200
  use_data_parallel: False

eval: False

logger:
  tensorboard: False
  matplotlib: True

seed: null
