name: simsiam-cifar10-colab
dataset:
  name: cifar10
  image_size: 32
  num_workers: 0

model:
  name: simsiam
  backbone: resnet18
  proj_layers: 2

train:
  optimizer:
    name: sgd
    weight_decay: 0.0005
    momentum: 0.9
  warmup_epochs: 5
  warmup_lr: 0
  base_lr: 0.03
  final_lr: 0
  num_epochs: 200
  stop_at_epoch: 200
  batch_size: 128
  source_pool_size: 1000
  source_subset_seed: 0
  knn_monitor: True
  knn_interval: 1
  knn_k: 200
  use_data_parallel: False

eval: False

# eval:
#   optimizer:
#     name: sgd
#     weight_decay: 0
#     momentum: 0.9
#   warmup_lr: 0
#   warmup_epochs: 0
#   base_lr: 30
#   final_lr: 0
#   batch_size: 128
#   num_epochs: 50
#   use_data_parallel: False

logger:
  tensorboard: False
  matplotlib: True

seed: null
