name: pseudo-supervised-stl10-colab
dataset:
  name: stl10
  image_size: 96
  num_workers: 0

model:
  name: pseudo_supervised_net
  backbone: resnet18

train:
  optimizer:
    name: sgd
    weight_decay: 0.0005
    momentum: 0.9
  warmup_epochs: 5
  warmup_lr: 0
  base_lr: 0.03
  final_lr: 0
  num_epochs: 100
  stop_at_epoch: 100
  batch_size: 128
  source_pool_size: 100
  augment_probability: 1.0
  source_subset_seed: 0
  knn_monitor: True
  knn_interval: 1
  knn_k: 200
  use_data_parallel: False

eval: False

logger:
  tensorboard: False
  matplotlib: True

seed: null
