name: simclr-cifar10-linear-eval
dataset:
  name: cifar10
  image_size: 32
  num_workers: 0

model:
  name: simclr
  backbone: resnet18

train: null

eval:
  optimizer:
    name: sgd
    weight_decay: 0
    momentum: 0.9
  warmup_lr: 0
  warmup_epochs: 0
  base_lr: 0.25
  final_lr: 0
  batch_size: 1024
  num_epochs: 100

logger:
  tensorboard: False
  matplotlib: True

seed: null
